proxy:
  secretToken: 97141abb55ea5321867979cb57bb2e6a86a2f4d6bb166fca45aedb07c212c42d
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
  chp:
    resources:
      requests:
        memory: 0
        cpu: 0
  imagePullSecret: &imagePullSecret
    enabled: true
    registry: gcr.io
    username: _json_key
    password: |-
      {
        "type": "service_account",
        "project_id": "dummy-gcp-project",
        "private_key_id": "asdfasdfasdfasdfasdfasdfasdfasdfasdfasdf",
        "private_key": "-----BEGIN PRIVATE KEY-----........-----END PRIVATE KEY-----\n",
        "client_email": "sa-name@dummy-gcp-project.iam.gserviceaccount.com",
        "client_id": "107124232533563852236",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/sa-name%40dummy-gcp-project.iam.gserviceaccount.com"
      }
  secretToken: 97141abb55ea5321867979cb57bb2e6a86a2f4d6bb166fca45aedb07c212c42d
  service:
    type: NodePort
    nodePorts:
      http: 31212

hub:
  cookieSecret: 1470700e01f77171c2c67b12130c25081dfbdf2697af8c2f2bd05621b31100bf
  db:
    type: sqlite-memory
  imagePullSecret: *imagePullSecret
  networkPolicy:
    enabled: true
  resources:
    requests:
      memory: 0
      cpu: 0
  services:
    test:
      admin: true
      apiToken: 0cc05feaefeeb29179e924ffc6d3886ffacf0d1a28ab225f5c210436ffc5cfd5

singleuser:
  imagePullSecret: *imagePullSecret
  memory:
    guarantee: null
  networkPolicy:
    enabled: true
    # Block all egress apart from DNS and jupyter.org
    # CIDR must match the allowed URL in test_singleuser_netpol
    egress:
      - ports:
        ## port 53 is the default port for DNS queries
        - port: 53
          protocol: UDP
      - to:
        ## nslookup jupyter.org
        ## - 104.28.9.110
        ## - 104.28.8.110
        - ipBlock:
            cidr: 104.28.9.110/32
        - ipBlock:
            cidr: 104.28.8.110/32
  storage:
    type: none

prePuller:
  hook:
    enabled: false

scheduling:
  userScheduler:
    enabled: true

debug:
  enabled: true
 
