
{{- if .Values.proxy.chp.imagePullSecret.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: proxy-chp-image-credentials
  labels:
    {{- $_ := merge (dict "componentSuffix" "-image-credentials") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "jupyterhub.dockerconfigjson" .Values.proxy.imagePullSecret }}
{{- end }}